version: '3'
services:

  pyspark:
    image: jupyter/all-spark-notebook:latest
    container_name: jupyter_pyspark
    working_dir: /home/jovyan/work
    ports:
    - 8888:8888/tcp
    - 4040:4040/tcp
    volumes:
    - ./job:/home/jovyan/work

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodb

  postgres:
    image: postgres:11.3
    container_name: postgres
    ports:
    - "5432:5432/tcp"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB : report
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080

